### ISSUE TITLE
`Errno::ENOENT` error in Event Manager

### ISSUE THREAD

**Issue by zeitchef** [TheOdinProject/ruby_course#129]
When switching over to using the `CSV` library in the Event Manager project, I get the following error when running the file:

```bash
EventManger Initialized!
Traceback (most recent call last):
	3: from lib/event_manager.rb:4:in `<main>'
	2: from /Users/scott/.rbenv/versions/2.5.0/lib/ruby/2.5.0/csv.rb:1272:in `open'
	1: from /Users/scott/.rbenv/versions/2.5.0/lib/ruby/2.5.0/csv.rb:1272:in `open'
/Users/scott/.rbenv/versions/2.5.0/lib/ruby/2.5.0/csv.rb:1272:in `initialize': No such file or directory @ rb_sysopen - event_attendess.csv (Errno::ENOENT)
```

Here's my `event_manager.rb` file:

```ruby
require 'csv'
puts 'EventManger Initialized!'

contents = CSV.open 'event_attendess.csv', headers: true, header_converters: :symbol
contents.each do |row|
  name = row[:first_name]
  puts name
end
```

Interestingly, I'm able to access the CSV file and work with it in Pry without problems.

**Comment by zeitchef** [comment]
Obviously, spelling the file name correctly would help greatly.
